name: Feeling Report
description: How are you today?
title: "I am "
labels: ["feelings"]
assignees:
  - dusunax
body:
 - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help everyone identify you!
  - type: dropdown
    id: feelings
    attributes:
      label: How are you feeling today?
      options:
        - 😶 Meh
        - 😄 Happy
        - ☹️ Sad
        - 😴 Sleepy
        - 🥳 Excited
        - 😫 Exhausted
        - 😱 Scared
        - 🤬 Angry
        - 😇 Blessed
        - 🥰 Loving
      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What Happened?
      description: Today is...
      placeholder: Tell us what happened!
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Extra fields
      options:
        - label: Take care yourself!
          required: true
        - label: Good bye🤚
