name: Pull Request Template
description: A template for pull requests
title: Pull Request Template
labels: [""]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help us review your pull request.
  - type: checkboxes
    id: pr_type
    attributes:
      label: PR Type 📝
      options:
        - label: 기능 추가 Feature addition
          value: feature_addition
        - label: 기능 삭제 Feature deletion
          value: feature_deletion
        - label: 버그 수정 Bug fix
          value: bug_fix
        - label: 코드 리팩토링 Refactoring
          value: refactoring
        - label: 의존성, 환경변수, 빌드 관련 코드 업데이트 Dependency, environment variables, build related code update
          value: dependency_update
        - label: 기타 Others
          value: others
    default: 0
    validations:
      required: true
  - type: textarea
    id: key_changes
    attributes:
      label: 🗂️ 주요 변경사항 Key Changes
  - type: textarea
    id: reviewer_notes
    attributes:
      label: 💬 리뷰어에게 전달할 점 Notes for Reviewer
  - type: checkboxes
    id: checks
    attributes:
      label: 반영 브랜치 branch check 👀
      options:
        - label: Is this PR targeting the correct branch?
          required: true
